services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8081:8081"
      - "5173:5173"
      - "5174:5174"
      - "3232:3232"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    
    env_file:
      - .env
    
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase

